### ISSUE TITLE
NumlockX cannot be enabled on post-install script.

### ISSUE THREAD

**Issue by FredBezies** [GnuLinuxViperr/Viperr-9#2]
Simple to reproduce.

1) Install Viperr
2) Post-install it accepting **every single option**.
3) Wait
4) Script is telling us numlockx is not found.

![numlockx](https://cloud.githubusercontent.com/assets/8571419/17622976/f7993148-609d-11e6-9695-c616864715cf.png)

**Comment by penthium2** [comment]
strange, this rmp is corectly installed under my vm

**Comment by FredBezies** [comment]
I tried again, skipping Chrome, flash and crawl sdl installation. No more bug. Which option is guilty here?

**Comment by penthium2** [comment]
so no more issue.

For Viperr 10 : add check for all install ok during post-install script
